FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN pip install mitmproxy==9.0.1

EXPOSE 8080

CMD ["mitmweb", "--web-host", "0.0.0.0", "--web-port", "8080", "--no-browser", "--set", "block_global=false"]